### ISSUE TITLE
Copy TicketID as... Markdown/Confluence/HTML

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#11]
The current clipboard content is HTML formatted, and is converted to plain text (without URL) when pasted into a text field. This does not help to write hyper-links in GitHub Pull-requests / JIRA records. 

Here is a Request to address the problem:
- Copy as Markdown Wiki: `[<Issue-ID>: <Issue-Headline>](<Issue-URL>)`
- Copy as Confluence Wiki: `[<Issue-ID>: <Issue-Headline>|<Issue-URL>]`
- Copy as Simple HTML: `<a href="<Issue-URL>"><Issue-ID>: <Issue-Headline></a>`

I do not know what is the current HTML format.

**Comment by ulybu** [comment]
- the issue headline can me quite long, may be add an option to limit its length
- currently investing a way to add a link in the rally text editor for issue (doesn't seems to support any kind of markup)

Currently being implemented in the [add_handlers](https://github.com/ulybu/rally-ext/tree/add_handlers) branch

**Comment by ulybu** [comment]
implemented in #13
