### ISSUE TITLE
Ticket flagging does not work with new Rally Feature List

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#19]
- Extension V0.5.1
- Portfolio Item Grid: https://rally1.rallydev.com/#/35063137037d/portfolioitemstreegrid

**Comment by ulybu** [comment]
Thanks for the feedback.

Works for me V0.5.1
- What doesn't work ?
- Can you see the copy-to-clipboard icons  (~ :clipboard:) ? 
- If yes, then does it copy something at all ? if yes, what does it copy ?

Please could you try again and report me those answer (they may overlap themselves) ?
**Also**, have a look at the js console, you may ran into #12

**Comment by ulybu** [comment]
Closing due to lack of infomation. Be happy to reoppen it if needed
