### ISSUE TITLE
The markdown syntax content is not what it claims to be

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#20]
- Claim: `[FE123: something good somewhere](https://xxx.rallydev.com/path/to/task)`
- Reality: `[FE123](https://xxx.rallydev.com/path/to/task)`

**Comment by ulybu** [comment]
Hi,
I'm pretty sure the trailing _`_ doesn't come from the extension
Could you PM or mail me the an example of a non working link/dashboard.. I can't reproduce that bug

**Comment by asnowfix** [comment]
The issue is not the leading `\``, but the fact that the clear-text includes the full ticket headline in one (the good) case & only the ticket number in the other (bad) case.

**Comment by ulybu** [comment]
yes I understood the issue. I can't reproduce it, could you PM or mail me the an example of a non working link/dashboard?

**Comment by ulybu** [comment]
Confirmed. Observed on a grid layout (kanban board)

**Comment by ulybu** [comment]
Fixed in 813f10f48d4a6f7c72f3a82ff1967cde7e8a330f

**Comment by asnowfix** [comment]
Fixed: thanks :-)
