### ISSUE TITLE
Copy to simple HTML should be text/html, not plain text...

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#21]
..so that pasting in an HTML-capable area (eg Outlook, Rally... etc) would give the HTML rendering result rather than the HTML considered as plain text.

Maybe some of the below could help?

``` javascript
clipboard.setData("text/plain", selection.getText());
clipboard.setData("application/officeObj", selection.serialize());
clipboard.setData("image/bmp", draw(selection));
clipboard.setData("text/html", ...);
```

See https://www.lucidchart.com/techblog/2014/12/02/definitive-guide-copying-pasting-javascript/

**Comment by ulybu** [comment]
That would be great, thanks for the tip :+1:

**Comment by ulybu** [comment]
Implemented in https://github.com/ulybu/rally-ext/releases/tag/0.6.2

Thanks for the suggestion

**Comment by asnowfix** [comment]
Thanks :-)

That would be even better with pasted text including (1) the ticket+headline rather than just (2) the ticket key. If only the key is required, it is possible to delete the excess text, the opposite being not possible.
