### ISSUE TITLE
Copy as Markdown wiki does not escape Markdown special caracters

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#22]
For example copy as markup of DE2059 from https://rally1.rallydev.com/#/35063137037d/detail/userstory/42447607777/defects gives `[DE2059: [T36][MP][CQPOD] The windows URL app format has changed, MP can't validate it](https://rally1.rallydev.com/#/35063137037d/detail/defect/41556977611)` which is invalid markdown: it should be `[DE2059: \[T36\]\[MP\]\[CQPOD\] The windows URL app format has changed, MP can't validate it](https://rally1.rallydev.com/#/35063137037d/detail/defect/41556977611)`

**Comment by ulybu** [comment]
Can you name a markdown parser that doesn't support `[DE2059: [T36][MP][CQPOD] The windows URL app format has changed, MP can't validate it](https://rally1.rallydev.com/#/35063137037d/detail/defect/41556977611)` ? 

Github does support it

**Comment by asnowfix** [comment]
Adobe Brackets use to not support it. I just double-checked & it works now.

**Comment by ulybu** [comment]
ok.
I couldn't find reference mentioning that those characters needed to be escaped. 
Also, it works fine on the [daring fireball 's online converter](http://daringfireball.net/projects/markdown/dingus). Will close the issue
