### ISSUE TITLE
Include ticket headline in simple HTML

### ISSUE THREAD

**Issue by asnowfix** [ulybu/rally-ext#23]
Follow-up of https://github.com/ulybu/rally-ext/issues/21 to take into account https://github.com/ulybu/rally-ext/issues/21#issuecomment-160763167

That would be even better with pasted text including (1) the ticket+headline rather than just (2) the ticket key. If only the key is required, it is possible to delete the excess text, the opposite being not possible.

**Comment by ulybu** [comment]
:white_check_mark: done with release 0.8.0
